name: Electron test/build

on: [push]

jobs:

  test:
    runs-on: macOS-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: tests
        run: yarn test
        env:
          CI: true

  build:
    needs: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: package
        run: yarn package
      - name: artifacts（mac)
        if: matrix.os == 'macOS-latest'
        run: |
          mkdir artifacts
          cp dist/*.dmg artifacts
      - name: artifacts（win)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          cp dist/*.exe artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ matrix.os }}
          path: artifacts
