name: Electron CI/CD

on: [push]

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: unit
        run: yarn unit
        CI: true
      - name: e2e
        run: yarn e2e
        CI: true
      - name: Build
        run: yarn package
      - name: Upload
        run: npx rimraf 'dist/!(*.exe|*.deb|*.AppImage|*.dmg)'
        uses: actions/upload-artifact@master
        with:
          name: artifact ${{ matrix.os }}
          path: dist

