name: Electron CI/CD

on: [push]

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
#      - name: unit
#        run: yarn unit
#      - name: e2e
#        run: yarn e2e
      - name: package
        run: yarn package
      - name: clean
        run: npx rimraf 'dist/!(*.exe|*.deb|*.AppImage|*.dmg)'
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ matrix.os }}
          path: dist

