name: Electron CI/CD

on: [push]

jobs:

  test:

    runs-on: macOS-latest

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: |
          yarn install
          echo "テストうまく動かないので一旦スルー"
#      - name: unit
#        run: yarn unit
#      - name: e2e
#        run: yarn e2e
      - name: Build
        run: yarn package
      - name: Publish
        run: echo "ここでパブリッシュ!!"
