name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: package
        run: yarn package
      - name: artifacts（mac)
        if: matrix.os == 'macOS-latest'
        run: |
          mkdir artifacts
          cp dist/*.dmg artifacts
      - name: artifacts（win)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          cp dist/*.exe artifacts
      - name: upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ matrix.os }}
          path: artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "artifacts/**"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
